# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e1da54cdfeff16746bb33b36b28324516fdb49ad88a0e4902d8c167bdbfa0a159c5d34f784a5da6b8c471d08b1a090b68305e3c3c74ba60ef7b166bdf817ffcf

test:
  secret_key_base: 0226e2d02042e3242c71ffdceac181b247523a630b7073a682c69bd51e638045ca675124b40bf7199bb4bf239f1e615a2e930f3c6c26acec6bd51f79c6214e60

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
